### ISSUE TITLE
Custom Phile Header

### ISSUE THREAD

**Issue by james2doyle** [PhileCMS/Phile#178]
This piggybacks off #166 a little. I think it would be cool to have a `X-Phile-Version: 1.3.0` header in the response. 

You can see examples of this in a bunch of sites. I actually saw that the WP-Super Cache plugin adds `WP-Super-Cache:Served supercache file from PHP` to the response.

**Comment by gexclaude** [comment]
Question is what you want to achieve with it. From a security point of view this is a technical information disclosure which gives an attacker the exact Phile version. So he would now that a) Phile is used and b) in which version. This makes it easier to find or make use of known vulnerabilities.

**Comment by Frodox** [comment]
@gexclaude +1
good to do it optional through the `config.php` in this case

**Comment by Schlaefer** [comment]
No strong opinion, but leaning to a No. It's a fancy gimmick, but as @gexclaude said it's usually not recommended to expose stack and version details (in header or template comments) for security reasons.

**Comment by james2doyle** [comment]
Ok that does make some sense. I think it could be nice "advertising" in having something there to show the site is running Phile. I usually check sites to see what they are running, hence the notes about the Wordpress plugins and such. 

So is it not worth having at all?

**Comment by Frodox** [comment]
> So is it not worth having at all?

Well, it is not totally bad, if there is some case of usage. I think it should be a configurable option, like `expose_php`, `ServerTokens` and `ServerSignature` and so on.

**Comment by Schlaefer** [comment]
OK, I vote for a single `<!-- Made with PhileCMS -->` in the default theme index.html `<head>` section.

- easy to spot and to remove if you inspect/customize the theme
- no complicated configuration for esoteric features like HTML-headers

**Comment by james2doyle** [comment]
+1

**Comment by X3msnake** [comment]
+1

**Comment by Schlaefer** [comment]
fixed in #223
