### ISSUE TITLE
[RFC] introduce a new develop branch/adopt gitflow

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#185]
I propose Phile adopts a branch structure that is commonly known as [gitflow](http://nvie.com/posts/a-successful-git-branching-model/#the-main-branches
). It looks a little bit complicated but is rather simple:

- a master branch which contains production ready releases only
- a develop branch which receives all pull request and active development changes
- feature branches for working on major features (optional)
  - branch from develop, work on the feature and merge back into develop when finished
- a release branch on release (optional):
  - branch a new release-branch from develop
  - finish up the release-branch (bump version string, resolve outstanding pull requests etc.)
  - merge it back into master (as the actual release with tag)
  - merge it into develop (to incorporate the last minute changes)
  - delete the release branch

**Comment by Frodox** [comment]
+1, Looks good for me.
Also it will be fine to create a wiki page with description of all branches for newbies:)

**Comment by james2doyle** [comment]
We are half doing it now with the different brand versions. So yes, it
makes sense to adopt it fully

On Saturday, February 7, 2015, Vit Ry <notifications@github.com> wrote:

> +1, Looks good for me.
> Also it will be fine to create a wiki page with description of all
> branches for newbies:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhileCMS/Phile/issues/185#issuecomment-73366119>.
>


-- 
*James Doyle*

*t:  @james2doyle <https://twitter.com/james2doyle>w: ohdoylerules.com
<http://ohdoylerules.com>*

**Comment by Schlaefer** [comment]
@Frodox Hopefully we don't need to write an extended description. One benefit should be that we can point to [existing sources](https://www.google.de/search?q=git+flow+tutorial).

I assume that the silence of @NeoBlack on the latest issues is a ringing endorsement? ;)

**Comment by james2doyle** [comment]
bump @NeoBlack

**Comment by Schlaefer** [comment]
develop branch is created
