### ISSUE TITLE
[BUG] Install with zip is broken, missing lib/vendor/autoload.php

### ISSUE THREAD

**Issue by Styn** [PhileCMS/Phile#188]
Warning: require(../lib/vendor/autoload.php) [function.require]: failed to open stream: No such file or directory in ../lib/Phile/Bootstrap.php on line 112

**Comment by Schlaefer** [comment]
Did you download the .zip from http://philecms.com/? This .zip should contain all necessary files incl. `lib/vendor`.

If you downloaded the .zip directly from github you need to install composer and run `composer install` (see the installation documentation).

**Comment by Styn** [comment]
I indeed got the zip from github. It might be useful to update the readme since it seems to imply composer isn't necessary when using git/zip 
cfr.: (unless you use git and zip files for everything)

Using the zip from philecms.com I get a different error however: Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/stijnlammens/public_html/lib/Phile/Core.php on line 65

I think the issue is somewhere in this changeset: https://github.com/PhileCMS/Phile/commit/d9076b26471b16e5a12e704b8fca215eaed994ad

I see charset being added to config, but it's getting fetched from the settings in registry, this doesn't seem right.

**Comment by Schlaefer** [comment]
> It might be useful to update the readme since it seems to imply composer isn't necessary when using git/zip 

You're are right, the install documentation is a little bit scattered, not in sync and not that clear at the moment. This needs to be improved.

Please don't hesitate to improve it yourself (via wiki or pull-request).

> Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/stijnlammens/public_html/lib/Phile/Core.php on line 65

Can you confirm that you're using PHP 5.4+? Phile requires PHP 5.4 and this looks like an error PHP 5.3- might trigger.

**Comment by Styn** [comment]
You are right, the server is running 5.3!
