### ISSUE TITLE
Page duplicates

### ISSUE THREAD

**Issue by makzav** [PhileCMS/Phile#192]
Page /content/sub/index.md can be requested as http://example.com/sub and http://example.com/sub/. In fact this is a two different pages with the same content and it is important to avoid page duplicates at least for search engines.

The same is with other combinations: /content/sub/page/index.md can be reached as http://example.com/sub/page and http://example.com/sub/page/.

Page duplicates needs to be redirected with 301 status code.

And what about optional trailing slash?

**Comment by makzav** [comment]
I see https://github.com/PhileCMS/Phile/pull/160/files has solution for preventing duplicates, but Phile 1.4.0 doesn't contain this.

**Comment by Schlaefer** [comment]
Short recap:

- Phile didn't care about a slash or no-slash
- Then #170 removed the `index` from `http://host/foo/index`. There's now an ambiguity in `http://host/foo/` (and `http://host/foo`). Is it `content/foo.md` or `content/foo/index.md`? Both are tested in that order at the moment. Phile still doesn't care about slashes.

So, should Phile be opinionated about slashes and if yes in which way?

I like what @kicken proposed in #198. Let's make it somewhat semantically sound: `http:/host/foo` means "page" and should point to `content/foo.md`. `http:/host/foo/` means "folder" and should point to `content/foo/index.md`.

At the same time Phile should resolve potential 'slash'-errors:

- `http:/host/foo` is requested and `content/foo.md` doesn't exist but `content/foo/index.md` → redirect to `http:/host/foo/`
- `http:/host/foo/` is requested and `content/foo/index.md` doesn't exist but `content/foo.md` → redirect to `http:/host/foo`

With those rules I would :+1:

**Comment by Stijn-Flipper** [comment]
> At the same time Phile should resolve potential 'slash'-errors:
> 
> - http:/host/foo is requested and content/foo.md doesn't exist but content/foo/index.md → redirect to http:/host/foo/
> - http:/host/foo/ is requested and content/foo/index.md doesn't exist but content/foo.md → redirect to http:/host/foo
>
> With those rules I would

I had a similar problem in a web project, we solved it the way as you described it. It just feels somehow natural and intuitive to do so.

**Comment by kicken** [comment]
:+1:

Sounds good to me to normalize the slash both ways depending on what structure is in place for the actual files.

**Comment by Schlaefer** [comment]
I made a new pull request #208 implementing those rules.

**Comment by Schlaefer** [comment]
fixed in #208
