### ISSUE TITLE
remove Feature Request wiki page

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#194]
https://github.com/PhileCMS/Phile/wiki/Feature-Requests

I don't think anyone addresses issues there anymore? Feature requests should be handled in the github issue tracker.

**Comment by Frodox** [comment]
+1

**Comment by Stijn-Flipper** [comment]
Yeah, I also agree with that since the issue page has plenty of space to discuss a feature.

**Comment by james2doyle** [comment]
+1

**Comment by Schlaefer** [comment]
Done
