### ISSUE TITLE
Index.html

### ISSUE THREAD

**Issue by A-Monkey** [PhileCMS/Phile#205]
Why is there empty index.html files in:

content/index.html
themes/index.html
lib/index.html
vendor/index.html
plugins/index.html

**Comment by james2doyle** [comment]
By default a git repo does not index empty folders. These empty files are
there to maintain the folder structure instead of adding more code to
manage the file system.

**Comment by A-Monkey** [comment]
Hi james !
Thanks for reply.
Ok, so it´s a Git thing...

So if I understand things right I can safely delete those empty index.html files.
(sorry I am a monkey)

**Comment by james2doyle** [comment]
yes you can delete them, if you dont plan on using git

**Comment by A-Monkey** [comment]
Cool thanks,

Just realized that ; ) (Used to see .gitignore files).
Well this looks very promising. Great introduction film! 
I have tried Stacey and Kirby before so now lets do Phile !
