### ISSUE TITLE
use Scrutinizer-CI

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#209]
[Scrutinizer](https://scrutinizer-ci.com/) inspects source code and points out potential problems in it.

[That's the result for Phile in my fork](https://scrutinizer-ci.com/g/Schlaefer/Phile/) and it looks "very good" as it is.

We could:

- get some insight into the code for free (as open source project)
- demonstrate that Phile takes code quality seriously
- show hip looking badges on the homepage
- prove that Phile's contributors are clever enough to tweak statistics
- establish that Phile is [totally green](https://www.youtube.com/watch?v=sRZh42fWLbg)!

Scrutinizer shouldn't be treated as a call to action or truth that Phile must obey to. It's just an additional tool.

**Comment by james2doyle** [comment]
+1

**Comment by NeoBlack** [comment]
looks really nice, I like it.
btw, many thx for all your work and time you invest in Phile.

**Comment by X3msnake** [comment]
Cool Mate.

:)

2015-03-11 19:36 GMT+00:00 Frank Nägler <notifications@github.com>:

> looks really nice, I like it.
> btw, many thx for all your work and time you invest in Phile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhileCMS/Phile/issues/209#issuecomment-78353179>.
>



-- 
Com os melhores cumprimentos,
Vinicius Silva

**Comment by Schlaefer** [comment]
Here it is: https://scrutinizer-ci.com/g/PhileCMS/Phile/

I opened a new PhileCMS organization at scrutinizer. @james2doyle @NeoBlack if you want to be admin for organization please register and give me the email-address so I can add you.

---

> btw, many thx for all your work and time you invest in Phile.

Thanks for the thumbs up. As @infostream said in another PR "You have something good here." and I agree.

My major issues are mostly resolved (easy install) or in progress (see the open refactoring PRs). There's a short list of minor/simple points (like emitting a 404 event). Also I a few ideas for features, but these are someday/maybe.
