### ISSUE TITLE
Phile icon is missing in errorHanlder in non-dev checkout

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#211]
https://github.com/PhileCMS/Phile/blob/master/plugins/phile/errorHandler/Icon.png

probably filtered by #200

**Comment by Stijn-Flipper** [comment]
:-1:

You don't have to rename the file, instead just remove [this line from `.gitattributes`](https://github.com/PhileCMS/Phile/blob/develop/.gitattributes#L2).

I've added it to `.gitattributes` on PR #200 because I thought it was some leftover development file.

**Comment by Schlaefer** [comment]
closed by 216
