### ISSUE TITLE
Commit composer.lock

### ISSUE THREAD

**Issue by james2doyle** [PhileCMS/Phile#217]
Apparently committing the `composer.lock` file helps with `composer install`. This suggestion comes from the [composer project lead](https://twitter.com/seldaek/status/578687656910983168). This was an issue posted before by @romqin, but we had closed it with saying we were going to refactor.

**Comment by Schlaefer** [comment]
Some people include it, some don't. You can argue for both cases. I tend to include it.

:+1: but no strong opinion

**Comment by romqin** [comment]
[Composer Best Practices](http://slides.seld.be/?file=2015-03-12+Composer+Best+Practices.html#43) by Jordi Boggiano.

**Comment by james2doyle** [comment]
Haha! Thanks @romqin
