### ISSUE TITLE
reorganize plugin wiki page

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#221]
https://github.com/PhileCMS/Phile/wiki/%5BCOMMUNITY%5D-Plugins

I think it would be more helpful to try to reorganize the plugin-wiki-page for features (parser, markup extension, embedding third party content, …) instead of origin (core-team vs. third party).

Also instead of presenting a static snapshot of the page on http://philecms.com/ a link is a better solution: doesn't depend on a homepage refresh (release) and is always up-to-date.

**Comment by Frodox** [comment]
> I think it would be more helpful to try to reorganize the plugin-wiki-page for features (parser, markup extension, embedding third party content, …) instead of origin (core-team vs. third party).
+1, good idea

**Comment by Stijn-Flipper** [comment]
Yeah, it should be easier to skim through the plugins so you can collect all the plugins you need to set up your own Phile blog. 

So yes, +1

**Comment by james2doyle** [comment]
+1

**Comment by Schlaefer** [comment]
OK, I tried to file plugins into categories, but there's still a Misc section.
