### ISSUE TITLE
[FEATURE REQUEST] Using Twig variables in content files

### ISSUE THREAD

**Issue by mithat** [PhileCMS/Phile#228]
Would be cool. For example:

```markdown
<!--
Title: Howdy!
Description: There's no place like home.
-->

...

The name of this page, "{{ page.title }}", is pretty lame.

```

Maybe not the best use case, but I think you get the idea.

**Comment by Schlaefer** [comment]
Firing up the template parser is slow. There are ambiguities (replace in code/pre/other peoples markup?). But mainly it's easy to do in a plugin. Rough and tough:

```php
class Plugin extends AbstractPlugin {

	protected $events = ['template_engine_registered' => 'twigifyContent'];

	public function twigifyContent($data) {
		$data['data']['content'] = $this->renderTwigString(
			$data['data']['content'],
			$data['data']
		);
	}

	public function renderTwigString($string, array $vars = []) {
		$loader = new \Twig_Loader_String();
		$engine = new \Twig_Environment($loader, ['autoescape' => false]);
		return $engine->render($string, $vars);
	}

}
```

So I'm not convinced for the core and :-1:

PS: What I actually miss is a `ServiceLocator\TemplateInterface::renderString()` to render a simple string in the default template-parser. It's handy in plugins (as in this example).
