### ISSUE TITLE
[QUESTION] How to do form processing?

### ISSUE THREAD

**Issue by mithat** [PhileCMS/Phile#230]
What's the recommended way to handle form processing (e.g. a contact form) in Phile? I've tried a few approaches but none have succeeded--though I'm not ruling out my own stupidity or the limitations of PHP's development server.

**Comment by Schlaefer** [comment]
It should be straight forward:

- write the contact form HTML on a page (remember: you can use raw HTML in markdown documents)
- in a plugin check for the form fields in `$_POST`
- send email

Every ordinary "contact form in PHP" tutorial on the net should get you going.

**Comment by mithat** [comment]
It looks like I was falling victim to the behavior of PHP's built-in development server. I am submitting forms to a PHP script in the root directory. When I try a submission with PHP's built-in server, I get 404. I just tested in an Apache-based environment, and it works as expected.

I suspect PHP's server assumes _everything_ is routed through `index.php`, even requests that end in `.php`.

**Comment by Schlaefer** [comment]
Ok. So I guess we can close this.
