### ISSUE TITLE
Site design / themes?

### ISSUE THREAD

**Issue by MatthiasKauer** [PhileCMS/Phile#235]
Hi,
I'm wondering how I can adjust the look of a Phile site. I suppose I'd be happy getting other colors and maybe a header image.I read the docs and googled for a while now, but I can't find much about getting another theme or developing. I'm a total noob when it comes to html/css unfortunately. 
Are there any pointers in the docs that I missed? Can I go out and find css files elsewhere and just drop them into a Phile folder somewhere or does it not work that way? 
Can I use pico themes or are they incompatible like the pico plugins?

Cheers,
Matthias

**Comment by Schlaefer** [comment]
Make yourself familiar with CSS and HTML. Any generic tutorial on the web will do. Then just edit the layout HTML in `themes/default/index.html` and the existing CSS in `themes/default/css/style.css`.

Essentially that's it. But it's always a good starting-point to duplicate the "default" theme folder to create a new theme (activate it in the main `config.php` file). 

PS: Please ignore the `themes/default/style.css`. This CSS file doesn't belong there and should be deleted.
