### ISSUE TITLE
some urls (that have base_url in them) are not served returning 404 - with solution

### ISSUE THREAD

**Issue by jpralves** [PhileCMS/Phile#245]
The is an issue that prevents urls that have some part of the "base_url" in them from being served.

test for reproducing the problem:
Place the root of the Phile under /phile
Change the .htaccess to point RewriteBase /phile

Now create a folder in content/sub called phile
Place an index.md in it.

then go to http://<thesite>/phile/sub/phile/

And get an 404 error.

You can solve the problem by changing the function getCurrentUrl() in lib/Phile/Core/Router.php
where:
  $url = str_replace($basePath, '', $url);
replace by:
       $url = substr($url, strlen($basePath));

regards,

João

**Comment by Schlaefer** [comment]
fixed in #246
