### ISSUE TITLE
Rethinking documentation

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#253]
The main intent is to reduce work for maintainers and making life easier for users. What bugs me: 
- Phile homepage is documentation source after installation: when a user changes the Phile homepage for a quick "Hello world" instant-gratification experience the documentation is gone.
- It's difficult to maintain the wiki documentation for different (unreleased/older) Phile versions.

Proposal: Put documentation into (a plugin and add it to) the source. Show it as menu item on the Phile installation homepage in a debug/development mode only:
- Provides full documentation in every Phile installation (bonus: offline-usage)
- Have the documentation for the specific Phile version installed available later (after the landing page is changed)
- Keeps documentation in-sync with the code by versioning it in the repository

Use the wiki for content that doesn't need to be in sync with the code or you want to update outside of the releases-cycle (list of third-party plugins, sites using Phile, …).

Also remove any documentation from philecms.com. It's hard to maintain and only duplicates the "truth". Just link to the documentation source folder on github.

**Comment by jacmoe** [comment]
I think the github wiki looks like shite and I do prefer to read the docs at philecms.com - very much!

How about having the docs at the phile homepage but render from github wiki?
I really like how that homepage docs page is styled - it looks, er.. stylish :)

Keep in mind that the docs helps attract new users and it would of course be silly to force anyone to load up a development mode site just to read them.

I suggest auto sync with github wiki.
I actually use a commit hook for my personal site to keep everything synced up..

**Comment by JazzMaster** [comment]
this is github. 'Git' with the program. Setup subversion or Just Git the docs. Problem solved. Anyhoo, needs some help. We start with the demo site, dive into meta parsing and fall to the ocean floor with internals. What the users want just isnt available. for example: basic blogging setup. You need to doc phile like grav is documented. The assumption, as -is with Pico is that composer is installable.You cant reload what you cant install.

**Comment by Schlaefer** [comment]
I'm closing this because I don't perceive it as bug, major issue or it aged without  feedback moving the issue forward. Please feel free to re-open and add more information.
