### ISSUE TITLE
Can not install Phile CMS

### ISSUE THREAD

**Issue by AlexL777** [PhileCMS/Phile#278]
Hello Developers!

I would like to work with your CMS and have installed it. But then appeared error messages on the front end. I've installed the Composer, but the component is symfony incomplete and **/symfony/component**.

Therefore, my shows the system by logging in to the backend always at fault. How you can help me.

Would be very helpful and thanks in advance.

**Comment by Frodox** [comment]
Which error did you get? Do you try to install usuall installation, or dev's ?
Do you use master/develop branch, or .zip from site?

I just install usual installation fine
