### ISSUE TITLE
htaccess and random file

### ISSUE THREAD

**Issue by JazzMaster** [PhileCMS/Phile#283]
your permissions are mucked up, resulting in the requirement of a empty html file all of the directories.
mind you, as is, this will require editing or will trip issues but Ive provided an htaccess. now, that said, I do loops around this and much much more on my site. Of note are the content hotlink prevention and similar 403 forbidden on direct access of files. Forget where I yanked it from, but who cares..this SHOULD be this way. md files should be LOADED, not directly referenced. markdownpad or whatever seems to crash wine so it might be vaporware. mebbe we need to document better. Its like those sfv and nfo files left with a torrent. nobody knows what to do with them but clearly they are plain text.

**Comment by JazzMaster** [comment]
[htaccess.txt](https://github.com/PhileCMS/Phile/files/181012/htaccess.txt)

**Comment by james2doyle** [comment]
It is difficult to add this to the project, assess it's impact, and read the changes, without using the features of git and Github. Can you submit this as a pull request?

**Comment by NeoBlack** [comment]
we should rethink about htaccess file in general. htaccess work only with apache, not with other webservers like nginx.
