### ISSUE TITLE
Release 1.7

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#291]
So let's get serious about releasing [1.7.0](https://github.com/PhileCMS/Phile/milestones/1.7.0) then? Is it possible to merge the existing PRs #284, #285 and #286 without conflict? If so, let's do it.

Otherwise I propose we merge #285 and #286 against _develop_ instead of _master_ first, then perform the usual [release dance](https://github.com/PhileCMS/Phile/wiki/%5BDEVELOPER%5D-Release-Guide) which includes merging develop into master ("was" #284).

**Comment by james2doyle** [comment]
I actually had to manually get those merged it, but they are all there in that big Develop PR

![](http://cl.ly/0f47140f3C0d/Image%202016-04-11%20at%208.05.23%20AM.png)

So I think we can just click the big green button and wrap this up

**Comment by Schlaefer** [comment]
> I actually had to manually get those merged it

Missed that. 👍 

> So I think we can just click the big green button and wrap this up

Green buttons shall be pushed! 👍

**Comment by james2doyle** [comment]
Closed with #284 and also [published the latest release as well](https://github.com/PhileCMS/Phile/releases/tag/1.7.0)
