### ISSUE TITLE
Tweaks for 2.* releases

### ISSUE THREAD

**Issue by james2doyle** [PhileCMS/Phile#293]
Looks like some of the 2.* stuff contains some of the information that was merge in 1.7.0

**Comment by Schlaefer** [comment]
Aside from the question how to proceed with 2.* in general, can you point to what you mean specifically?

**Comment by james2doyle** [comment]
It seems like I mixed up the release for 2.x and [this release draft](https://github.com/PhileCMS/Phile/releases/tag/untagged-562d9652c7841ceb1e09)

**Comment by NeoBlack** [comment]
maybe a side-effect or reason for our problem wit h composer (#294) ?

**Comment by Schlaefer** [comment]
Ah. That was just the template for the "next" release as in "nobody knows if it will be 1.7.2 or 1.8.0".

I have the habit of setting up a new empty "next" release note right after a release is done. Then every time an issue is resolved or a PR is merged you can immediately write down a changlog line or other important info as long as the full context is in your head anyway.

In my experience it's much less time consuming and generates better quality content than writing it up later.
