### ISSUE TITLE
Can't install Phile 1.7.0 with composer

### ISSUE THREAD

**Issue by Schlaefer** [PhileCMS/Phile#294]
Please report your issue with the following information:

### Excpected behavior

Phile installs via composer by the officially encouraged command.

### Actual behavior

```bash
$ composer create-project --no-dev phile-cms/phile

Installing phile-cms/phile (1.6.0)
  - Installing phile-cms/phile (1.6.0)
    Loading from cache

Created project in /Users/siezi/Desktop/test_phile/phile
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phile-cms/plugin-installer-plugin 1.0.2 -> satisfiable by phile-cms/plugin-installer-plugin[1.0.2].
    - phile-cms/plugin-installer-plugin 1.0.2 requires composer-plugin-api 1.0.0 -> no matching package found.
```

### Steps to reproduce the behavior

run ```composer create-project --no-dev phile-cms/phile```

### Additional information

I just wanted to do check that 1.7 composer installation runs through but it failed. I believe it's related to removing the version information from composer.json in #286.

**Comment by NeoBlack** [comment]
on packagist.org the latest version is 1.6.0: https://packagist.org/packages/phile-cms/phile
also an update not work. this is strange, because in other projects like TYPO3, the composer.json does not contains a version information.
tagging should be enough. This must be investigated, because the recommendation by composer is, to not add the version information.

**Comment by NeoBlack** [comment]
Just for your information: I have added you and @james2doyle as maintainer to the packagist projects.

**Comment by Schlaefer** [comment]
> tagging should be enough

As I said in #286, this is my understanding and experience on other projects too. I tried in 1.5.0 but ran into similar problems. Afair I spend some time looking into the issue, but in the end it wasn't worth investigating further (setting up new test project on packagist, diving into composer debugging, …)

I guess what I want to say is that I'm willing to accept the will of the coding-gods on this matter. Let's include the version string in the composer file and call it a day.

But more power to anyone who's able to figure it out! 😄

**Comment by kicken** [comment]
Not sure what happened, but the changes from #286 seem to be missing on both the master branch and the 1.7.0 tag.  The composer.json file there still has listed in it `"version": "1.6.0"` which might be why packagist doesn't show a 1.7.0 version.

**Comment by james2doyle** [comment]
Is it possible that Packagist now expects a version property and since it
is removed it can't find a later version?

**Comment by kicken** [comment]
> Is it possible that Packagist now expects a version property and since it
> is removed it can't find a later version?

If you check the [1.7.0 tag's composer.json](https://github.com/PhileCMS/Phile/blob/1.7.0/composer.json#L3) file it still has the version property in it.  I think Packagist is seeing this and overriding the 1.7.0 tag with the 1.6.0 specified in composer.json.

Somehow the changes to remove the version seem to have never made it in.

**Comment by james2doyle** [comment]
So should the version be removed or bumped to 1.7.0?

**Comment by kicken** [comment]
Removed I think.  Without the version property it should pick up the version by the tag name.

**Comment by NeoBlack** [comment]
what do you think about a new release with the version number 1.7.1 to make sure packagist are updated correctly and the problem is fixed now?

**Comment by Schlaefer** [comment]
Agree. I wiped up a release in #297. Let's see if the test run through.

**Comment by NeoBlack** [comment]
packagist,org is up-to-date
