### ISSUE TITLE
PHP 7.4+ deprecates array_key_exists() on objects

### ISSUE THREAD

**Issue by CasualRascal** [PhileCMS/Phile#336]
With PHP version 7.4 and up, the following error appears and everything breaks

    Whoops\Exception\ErrorException thrown with message "array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead"

**Comment by Schlaefer** [comment]
Thanks for reporting. :+1: 

For anybody running into this issue: removing the whole Registry::offsetExists method should solve that issue. 

I'll try to fix that (and other minor issues) in a bugfix release in the upcoming weeks.
