### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by james2doyle** [PhileCMS/Phile#58]
Something we never really discussed. But my blog is getting close to 100 articles on a single page. I would like to split them.

I was thinking something like `example.com/2` would load the second chunk of pages based on `$config["posts_per_page"]` or a similar style.

So I am thinking of building a plugin for this. Does anyone have any conventions before I start?

**Comment by Stijn-Flipper** [comment]
> I'm starting work on a plugin.

Oh well.. I'm glad that there was actually a pagination issue

@james2doyle I just published an actual pagination plugin: [Phile Paginator](https://github.com/Stijn-Flipper/philePaginator) . It works really fine on both Apache and Nginx (remote uses nginx and local is Apache2). :smiley:

I'm not sure if we can integrate some of the ideas from this plugin in the core? I'm also fine if we leave it as a plugin extension (e.g. some people doesn't want pagination at all).
